imu0:
  T_i_b:
  - [1.0, 0.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0, 0.0]
  - [0.0, 0.0, 1.0, 0.0]
  - [0.0, 0.0, 0.0, 1.0]
  accelerometer_noise_density: 0.00097962
  accelerometer_random_walk: 0.00017475
  gyroscope_noise_density: 0.00013417
  gyroscope_random_walk: 2.75e-06
  model: calibrated
  rostopic: /imu0
  time_offset: 0.0
  update_rate: 495.0
